# This configuration was used Ebert to review the devopsdays/devopsdays-cli repository
# on 64d759904ea5d9b1add1270a54b77d2e8e004bef.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  fixme:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- testdata

